"""initial schema

Revision ID: 0d92ca3bcfcc
Revises: 
Create Date: 2026-09-30 12:26:13.086573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d92ca3bcfcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_code', sa.String(length=20), nullable=False),
    sa.Column('unit_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('unit_code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'industry_partner', 'system_admin', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('industry_partners',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admission_no', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=150), nullable=False),
    sa.Column('year_of_study', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('year_of_study BETWEEN 1 AND 4', name='ck_students_year_of_study'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('admission_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('system_admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('grade_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    with op.batch_alter_table('grade_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_profiles_student_id'), ['student_id'], unique=False)

    op.create_table('internship_opportunities',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('date_posted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['industry_partners.partner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    with op.batch_alter_table('internship_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internship_opportunities_partner_id'), ['partner_id'], unique=False)

    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['internship_opportunities.opportunity_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_student_id'), ['student_id'], unique=False)

    op.create_table('grades',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('grade_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('grade_value BETWEEN 0 AND 100', name='ck_grades_value_range'),
    sa.ForeignKeyConstraint(['profile_id'], ['grade_profiles.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['academic_units.unit_id'], ),
    sa.PrimaryKeyConstraint('grade_id'),
    sa.UniqueConstraint('profile_id', 'unit_id', name='uq_grades_profile_unit')
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_unit_id'), ['unit_id'], unique=False)

    op.create_table('opportunity_precursors',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['internship_opportunities.opportunity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['academic_units.unit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id', 'unit_id')
    )
    with op.batch_alter_table('opportunity_precursors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_precursors_unit_id'), ['unit_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['internship_opportunities.opportunity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_student_id'), ['student_id'], unique=False)

    op.create_table('placement_records',
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ongoing', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['internship_opportunities.opportunity_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('placement_id')
    )
    with op.batch_alter_table('placement_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_records_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_placement_records_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_placement_records_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_placement_records_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_placement_records_application_id'))

    op.drop_table('placement_records')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_student_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_opportunity_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('opportunity_precursors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_precursors_unit_id'))

    op.drop_table('opportunity_precursors')
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_unit_id'))
        batch_op.drop_index(batch_op.f('ix_grades_profile_id'))

    op.drop_table('grades')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_student_id'))
        batch_op.drop_index(batch_op.f('ix_applications_opportunity_id'))

    op.drop_table('applications')
    with op.batch_alter_table('internship_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internship_opportunities_partner_id'))

    op.drop_table('internship_opportunities')
    with op.batch_alter_table('grade_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_profiles_student_id'))

    op.drop_table('grade_profiles')
    op.drop_table('system_admins')
    op.drop_table('students')
    op.drop_table('industry_partners')
    op.drop_table('users')
    op.drop_table('academic_units')
    # ### end Alembic commands ###
