"""opportunity requirements and engine fields

Revision ID: 1c2e064aa78d
Revises: 0d92ca3bcfcc
Create Date: 2026-09-30 12:58:54.147748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2e064aa78d'
down_revision = '0d92ca3bcfcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_level', sa.SmallInteger(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    with op.batch_alter_table('internship_opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slots', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('application_deadline', sa.Date(), nullable=True))

    with op.batch_alter_table('opportunity_precursors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance', sa.Enum('essential', 'desirable', name='requirement_importance'), server_default='essential', nullable=False))
        batch_op.add_column(sa.Column('min_mark', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meets_requirements', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('avg_requirement_mark', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('unmet_requirements', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.create_unique_constraint('uq_recommendations_student_opportunity', ['student_id', 'opportunity_id'])

    # ### end Alembic commands ###

    # Added by hand: autogenerate does not detect CHECK constraints on existing tables.
    op.create_check_constraint('ck_academic_units_year_level', 'academic_units',
                               'year_level BETWEEN 1 AND 4')
    op.create_check_constraint('ck_opportunities_status', 'internship_opportunities',
                               "status IN ('open','closed')")
    op.create_check_constraint('ck_opportunities_slots', 'internship_opportunities', 'slots >= 1')
    op.create_check_constraint('ck_precursors_min_mark', 'opportunity_precursors',
                               'min_mark IS NULL OR min_mark BETWEEN 0 AND 100')


def downgrade():
    op.drop_constraint('ck_precursors_min_mark', 'opportunity_precursors', type_='check')
    op.drop_constraint('ck_opportunities_slots', 'internship_opportunities', type_='check')
    op.drop_constraint('ck_opportunities_status', 'internship_opportunities', type_='check')
    op.drop_constraint('ck_academic_units_year_level', 'academic_units', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_recommendations_student_opportunity', type_='unique')
        batch_op.drop_column('generated_at')
        batch_op.drop_column('unmet_requirements')
        batch_op.drop_column('avg_requirement_mark')
        batch_op.drop_column('meets_requirements')

    with op.batch_alter_table('opportunity_precursors', schema=None) as batch_op:
        batch_op.drop_column('min_mark')
        batch_op.drop_column('importance')

    with op.batch_alter_table('internship_opportunities', schema=None) as batch_op:
        batch_op.drop_column('application_deadline')
        batch_op.drop_column('slots')
        batch_op.drop_column('duration_months')

    with op.batch_alter_table('academic_units', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('year_level')

    # ### end Alembic commands ###
